In [1]:
from data_base import GLOBAL_DATA_BASE
from pathlib import Path
from classes import Portfolio
import numpy as np
from copy import deepcopy

current_path = Path.cwd()
GLOBAL_DATA_BASE = GLOBAL_DATA_BASE

In [5]:
portfolio = Portfolio(GLOBAL_DATA_BASE,"NC")
portfolio_global = deepcopy(portfolio)
portfolio_global.data_base.columns = ["Dono","Data","Ativo","C/V","Preço","Qnt","Moeda","Classe"]
mask1 = portfolio_global.data_base["Classe"] == "Tesouro"
mask2 = portfolio_global.data_base[mask1]["Ativo"] == "LFTS11"
display(portfolio_global.data_base[mask1])
# Create a combined mask
mask = mask1 & (~mask2)

# Update 'Qnt'
portfolio_global.data_base.loc[mask, "Qnt"] = (
    portfolio_global.data_base.loc[mask, "Qnt"].apply(lambda value: 100 * value)
)

# Update 'Preço'
portfolio_global.data_base.loc[mask, "Preço"] = (
    portfolio_global.data_base.loc[mask, "Preço"].apply(lambda value: np.round(value / 100, 2))
)
portfolio_global.data_base["Qnt"] = portfolio_global.data_base["Qnt"].apply(int)
display(portfolio_global.data_base[mask1])
dict_tipo = {True:"C",False:"V"}
portfolio_global.data_base["C/V"] = portfolio_global.data_base["C/V"].apply(lambda value: dict_tipo[value])

portfolio_global.data_base.drop("Classe",axis=1,inplace=True)

portfolio_global.data_base.to_csv(current_path/"historico_transacoes.csv", index=False)

        Dono       Data           Ativo    C/V     Preço    Qnt Moeda   Classe
4       Luiz 2025-04-17          LFTS11   True    132.11  16.00   BRL  Tesouro
6       Luiz 2025-04-17      IPCA+ 2050   True    780.73   1.93   BRL  Tesouro
7    Luciane 2025-04-16          LFTS11  False    131.95  17.00   BRL  Tesouro
15   Luciane 2025-04-16      Selic 2029  False  16326.00   0.07   BRL  Tesouro
16   Luciane 2025-04-06      IPCA+ 2050   True    769.19   5.26   BRL  Tesouro
..       ...        ...             ...    ...       ...    ...   ...      ...
502     Luiz 2023-09-21      IPCA+ 2029   True   3090.13   0.03   BRL  Tesouro
503     Luiz 2023-09-21  Prefixado 2029   True    574.65   0.18   BRL  Tesouro
534     Luiz 2023-05-29      Selic 2026   True  13263.25   0.08   BRL  Tesouro
535     Luiz 2023-05-29  Prefixado 2029   True    546.12   1.84   BRL  Tesouro
536     Luiz 2023-05-29      IPCA+ 2029   True   3019.33   0.17   BRL  Tesouro

[82 rows x 8 columns]

        Dono       Data           Ativo    C/V   Preço  Qnt Moeda   Classe
4       Luiz 2025-04-17          LFTS11   True  132.11   16   BRL  Tesouro
6       Luiz 2025-04-17      IPCA+ 2050   True    7.81  193   BRL  Tesouro
7    Luciane 2025-04-16          LFTS11  False  131.95   17   BRL  Tesouro
15   Luciane 2025-04-16      Selic 2029  False  163.26    7   BRL  Tesouro
16   Luciane 2025-04-06      IPCA+ 2050   True    7.69  526   BRL  Tesouro
..       ...        ...             ...    ...     ...  ...   ...      ...
502     Luiz 2023-09-21      IPCA+ 2029   True   30.90    3   BRL  Tesouro
503     Luiz 2023-09-21  Prefixado 2029   True    5.75   18   BRL  Tesouro
534     Luiz 2023-05-29      Selic 2026   True  132.63    8   BRL  Tesouro
535     Luiz 2023-05-29  Prefixado 2029   True    5.46  184   BRL  Tesouro
536     Luiz 2023-05-29      IPCA+ 2029   True   30.19   17   BRL  Tesouro

[82 rows x 8 columns]